// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ephwmhikhiiyrnikvrwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwaHdtaGlraGlpeXJuaWt2cndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1ODA4NDYsImV4cCI6MjA4MjE1Njg0Nn0.lfmC_BTyp4txlLeo_rd9UQMSU0LXbrxqhpvxEIb6w_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
